[22기 김한준]
wecode-bootcamp-korea/22-1st-DrMozzarella-backend pull request #10
Opened 2021-07-09 03:04 UTC by hanjkim10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-09 06:16 UTC, Kang-kyunghun requested changes

2021-07-09 06:16 UTC, Kang-kyunghun commented on accounts/views.py
> +        name = Account.objects.get(email=data["email"])
1. keyerror가 발생 할 수 있는 상황입니다.
2. email이 db에 없을 경우에 대한 예외 처리 추가해 주세요.
```suggestion
        user = Account.objects.get(email=data["email"])
```

2021-07-09 06:16 UTC, Kang-kyunghun commented on accounts/views.py
> +            return JsonResponse({"MESSAGE":"INVALID_NAME"}, status = 401)
해당 예외처리를 사용한 이유를 코멘트로 남겨주세요.

2021-07-09 06:16 UTC, Kang-kyunghun commented on accounts/views.py
> +                access_token = jwt.encode({"name":name.pk}, SECRET_KEY, algorithm = 'HS256')
```suggestion
                access_token = jwt.encode({"user_id":user.id}, SECRET_KEY, algorithm = 'HS256')
```
name이라는 변수보다는 user가 더 어울리는 변수입니다.

2021-07-09 07:40 UTC, hanjkim10 commented on accounts/views.py
> +            return JsonResponse({"MESSAGE":"INVALID_NAME"}, status = 401)
<img width="482" alt="스크린샷 2021-07-09 오후 4 38 05" src="https://user-images.githubusercontent.com/77793868/125041724-0b2b2e80-e0d4-11eb-9927-42b4ebd9c182.png">

40번째 줄 name의 데이터가 존재하지 않을때를 생각해서 ValueError, Invalid Name을 사용했습니다.
그러나 try문 안으로 넣으면서 필요가 없기때문에 삭제했습니다

2021-07-09 07:40 UTC, hanjkim10 commented on accounts/views.py
> +                access_token = jwt.encode({"name":name.pk}, SECRET_KEY, algorithm = 'HS256')
넵 수정했습니다

2021-07-09 07:41 UTC, hanjkim10 commented on accounts/views.py
> +        name = Account.objects.get(email=data["email"])
넵 try문 안으로 넣어 KeyError 상황을 처리하고 email이 db에 없는 경우도 조건을 넣어 수정했습니다

2021-07-09 07:57 UTC, Kang-kyunghun requested changes

2021-07-09 07:57 UTC, Kang-kyunghun commented on accounts/views.py
> +                return JsonResponse({"MESSAGE":"NOT EXISTED EMAIL"}, status = 400)
email이 틀렸을 경우와 비밀번호가 틀렸을 경우 보안의 이유로 에러 메시지를 통일할 필요가 있습니다. 
```suggestion
                return JsonResponse({"MESSAGE":"INVALID USER"}, status = 400)
```

2021-07-09 07:57 UTC, Kang-kyunghun commented on accounts/views.py
> +            return JsonResponse({"MESSAGE":"INVALID ERROR"}, status = 400)
```suggestion
            return JsonResponse({"MESSAGE":"INVALID USER"}, status = 400)
```
위와 같은 이유로 다음과 같이 바꿔주면 좋을 것 같아요

2021-07-09 10:30 UTC, hanjkim10 commented on accounts/views.py
> +                return JsonResponse({"MESSAGE":"NOT EXISTED EMAIL"}, status = 400)
넵 수정했습니다-!

2021-07-09 10:30 UTC, hanjkim10 commented on accounts/views.py
> +            return JsonResponse({"MESSAGE":"INVALID ERROR"}, status = 400)
넵 수정했습니다-!

2021-07-12 06:25 UTC, Kang-kyunghun requested changes

2021-07-12 06:25 UTC, Kang-kyunghun commented on accounts/views.py
> +                return JsonResponse({"MESSAGE":"INVALID USER"}, status = 400)
왜 exists()을 사용하는지, 그리고 exists()을 사용할 때 주로 어떤 method 다음에 사용하는지 조사해 보세요.

2021-07-12 06:25 UTC, Kang-kyunghun commented on accounts/views.py
> +            return JsonResponse({"MESSAGE":"KEY ERROR"}, status = 401)
status code 400과 401의 내용을 코멘트로 남겨주세요.

2021-07-12 07:37 UTC, hanjkim10 commented on accounts/views.py
> +                return JsonResponse({"MESSAGE":"INVALID USER"}, status = 400)
db에 있는 정보를 찾기위해 exists()를 사용하고 exists()를 사용할 때에는 get이 아닌 filter를 사용하기 때문에 filter method로 수정했습니다!

2021-07-12 07:38 UTC, hanjkim10 commented on accounts/views.py
> +            return JsonResponse({"MESSAGE":"KEY ERROR"}, status = 401)
400 - bad request 해당 요청이 잘못되었을때
401 - unauthorized 요청을 진행하기 위해 회원가입 또는 로그인이 먼저 진행되어야 할때

400으로 수정했습니다!

2021-07-12 08:58 UTC, Kang-kyunghun commented
LGTM~~!! 👍

2021-07-12 08:59 UTC, merged