Feature/navigation
wecode-bootcamp-korea/22-1st-DrMozzarella-backend pull request #11
Opened 2021-07-09 04:26 UTC by dom-lee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 네비게이션바에 필요한 데이터 엔드포인트
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 00:42 UTC, Kang-kyunghun requested changes

2021-07-12 00:42 UTC, Kang-kyunghun commented on products/views.py
> +            }
menu.name을 key 값으로 잡았는데, 그냥 menu.id랑 같은 위치에 있는 것은 어떤까요?
```suggestion
            results = {
                "menu_id"    : menu.id,
                "menu_name : manu.name,
                "categories" : [
                    {
                        "category_id" : category.id,
                        "name"        : category.name,
                        "image_url"   : category.image_url
                    } for category in menu.category_set.all()]
            } for manu in Menu.objects.all()
```

2021-07-12 00:42 UTC, Kang-kyunghun commented on drmozzarella/urls.py
> +    path('meta'     , MetaView.as_view()),
제가 처음에 meta data니까 meta로 가는 것이 좋다고 알려 드렸었는데, 
주고 있는 데이터나, restful을 따져 봤을 때 다음과 같이 바꾸는 것이 좋을 것 같아요.
```suggestion
    path('menus'     , MetaView.as_view()),
```

2021-07-12 00:42 UTC, Kang-kyunghun commented on products/views.py
> +class MetaView(View):
```suggestion
class MenuView(View):
```
위의 url과 같은 이유에요.

2021-07-12 06:31 UTC, dom-lee commented on drmozzarella/urls.py
> +    path('meta'     , MetaView.as_view()),
수정하였습니다.

2021-07-12 06:31 UTC, dom-lee commented on products/views.py
> +class MetaView(View):
수정하였습니다.

2021-07-12 09:00 UTC, Kang-kyunghun commented
category description 추가 안 하기로 하신건가요?

2021-07-12 11:10 UTC, dom-lee reviewed
category_description추가 및 프론트엔드 요청으로 JSON key의 이름 변경하였습니다.

2021-07-12 11:10 UTC, dom-lee commented on products/views.py
> +            }
프론트엔드가 구현해놓은게 너무 많아, list로 변경하기가 어려울것 같습니다.

2021-07-12 14:01 UTC, dom-lee commented
프론트엔드에서 category_id만을 가지고 현재 JSON 구조에서 해당 카테고리의 image_url과 description을 가져오기 어렵다고 하여, 구조를 다시 고안중에 있습니다.

2021-07-13 04:48 UTC, Kang-kyunghun commented
LGTM~!!

2021-07-13 04:48 UTC, merged