[22기 이동명] 주문 엔드포인트
wecode-bootcamp-korea/22-1st-DrMozzarella-backend pull request #19
Opened 2021-07-13 04:30 UTC by dom-lee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니에 있는 제품 주문하는 엔드포인트
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 09:21 UTC, dom-lee commented
![image](https://user-images.githubusercontent.com/46280353/125426427-e774e966-c997-422b-bedf-4b9db5a873ce.png)
![image](https://user-images.githubusercontent.com/46280353/125426477-ef7d9224-45e0-439d-871c-475a347d3f8b.png)
![image](https://user-images.githubusercontent.com/46280353/125426641-6ae50f8d-7192-4050-a169-f6665e3c6c5d.png)
![image](https://user-images.githubusercontent.com/46280353/125426776-7e34fa7d-52ec-4590-862e-2ddc4e03f7b6.png)

2021-07-14 02:01 UTC, Kang-kyunghun requested changes

2021-07-14 02:01 UTC, Kang-kyunghun commented on orders/urls.py
> +    path('/<int:order_id>/<int:order_item_id>' , OrderView.as_view()),
```suggestion
    path('/<int:order_id>/order-items/<int:order_item_id>' , OrderView.as_view()),
```
이게 조금 더 RESTful한 것 같습니다.

2021-07-14 02:01 UTC, Kang-kyunghun commented on orders/views.py
> +            if carts:
```suggestion
            if carts.exists():
```
존재 유무 같은 경우 exists()을 사용해 주세요.

2021-07-14 02:01 UTC, Kang-kyunghun commented
Transaction 한 번 조사해 보고 적용해 보세요.

2021-07-14 05:00 UTC, dom-lee commented on orders/urls.py
> +    path('/<int:order_id>/<int:order_item_id>' , OrderView.as_view()),
order_id만 받도록 urls.py 수정하였습니다.

2021-07-14 05:00 UTC, dom-lee commented on orders/views.py
> +            if carts:
수정하였습니다.

2021-07-14 05:02 UTC, dom-lee commented
django.db의 transaction.atomic() `with`문으로 transaction 처리하였습니다.
connection.close()로 중간에 연결 끊어서 원복되는지 확인하였습니다.

2021-07-14 05:04 UTC, dom-lee commented
![image](https://user-images.githubusercontent.com/46280353/125564395-7c185408-66b7-4a0f-b6aa-4eb06aeade0d.png)

2021-07-14 09:33 UTC, Kang-kyunghun commented
고생 많았어요~~!!

2021-07-14 09:33 UTC, merged