회원가입
wecode-bootcamp-korea/22-1st-DrMozzarella-backend pull request #5
Opened 2021-07-08 04:50 UTC by hanjkim10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 로그인 분리
- products view.py 삭제
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-08 04:51 UTC, hanjkim10 commented
![스크린샷 2021-07-08 오후 1 47 30](https://user-images.githubusercontent.com/77793868/124864285-9f719480-dff3-11eb-8e7b-109aeb88220d.png)

2021-07-08 09:17 UTC, Kang-kyunghun requested changes

2021-07-08 09:17 UTC, Kang-kyunghun commented on accounts/views.py
> +from django.views import View
```suggestion
from django.http  import JsonResponse
from django.views import View
```

2021-07-08 09:17 UTC, Kang-kyunghun commented on accounts/views.py
> +from my_settings import SECRET_KEY
```suggestion
from accounts.models import Account
from my_settings     import SECRET_KEY
```

2021-07-08 09:17 UTC, Kang-kyunghun commented on accounts/views.py
> +
공백은 1칸으로 해주세요.

2021-07-08 09:17 UTC, Kang-kyunghun commented on accounts/views.py
> +        PASSWORD_REGES     = '[A-Za-z0-9@#$%^&+=]{8,}'
```suggestion
        EMAIL_REGES    = "^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
        PASSWORD_REGES = '[A-Za-z0-9@#$%^&+=]{8,}'
```
= 기준으로 맞출 때 가장 긴 변수 기준으로 맞춰주면 됩니다.

2021-07-08 09:17 UTC, Kang-kyunghun commented on accounts/views.py
> +            return JsonResponse ({"MESSAGE":"잘못된 이메일 형식입니다."}, status = 400)
에러 메시지 같은 경우 영어로 해주세요.

2021-07-08 09:17 UTC, Kang-kyunghun commented on db_uploader.py
> +import os
db_uploader.py은 gitinore에 추가해 주시고 github에는 안 올라오게 해주세요.

2021-07-08 10:17 UTC, hanjkim10 commented on accounts/views.py
> +
넵 1칸으로 수정했습니다

2021-07-08 10:17 UTC, hanjkim10 commented on accounts/views.py
> +        PASSWORD_REGES     = '[A-Za-z0-9@#$%^&+=]{8,}'
냅 수정했습니다

2021-07-08 10:17 UTC, hanjkim10 commented on accounts/views.py
> +            return JsonResponse ({"MESSAGE":"잘못된 이메일 형식입니다."}, status = 400)
에러 메시지 영어로 수정했습니다

2021-07-08 10:17 UTC, hanjkim10 commented on db_uploader.py
> +import os
gitignore에 추가했습니다

2021-07-09 01:42 UTC, Kang-kyunghun requested changes

2021-07-09 01:42 UTC, Kang-kyunghun commented on accounts/views.py
> +        try:
다음 2가지를 코멘트로 남겨주세요.
1. keyerror가 발생하는 이유
2. try문을 코드 중간에서 시작한 이유

2021-07-09 01:42 UTC, Kang-kyunghun commented
uploader 파일 gitignor에 추가는 되었지만, 아직 PR에는 남아 있습니다. 제거 후 올려주세요.

2021-07-09 02:24 UTC, hanjkim10 commented on accounts/views.py
> +        try:
1. try문 안에 있는 name, password, email, address 중 누락 발생시 keyerror가 발생합니다

2. try문 전에 if 문으로 이메일 형식, 패스워드 형식, 중복되는 이메일을 먼저 필터링을 하고 try문을 시작하려 했는데 이게 효율적이지 못해 수정해서 다시 올렸습니다.

2021-07-09 02:38 UTC, merged

2021-07-09 02:41 UTC, Kang-kyunghun commented
LGTM~!