카테고리 페이지
wecode-bootcamp-korea/22-1st-DrMozzarella-backend pull request #8
Opened 2021-07-09 02:31 UTC by heesu-ahn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카테고리별 품목 리스트
- 정렬 옵션에 따른 재정렬
		 
## 수정 사항들 자세한 내용
- 쿼리 파라미터에 따라서 정렬이 다새 되도록

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-09 02:32 UTC, heesu-ahn commented
급하게 올리느라 컨벤션을 확인 안해서 최초 PR 작성후 다시 올릴 예정입니다

2021-07-09 03:00 UTC, heesu-ahn commented
![image](https://user-images.githubusercontent.com/77618489/125016960-2cc4ef80-e0ad-11eb-9e69-987e5487c943.png)
포스트맨 화면 스크린 샷 입니다

2021-07-09 05:50 UTC, Kang-kyunghun requested changes

2021-07-09 05:50 UTC, Kang-kyunghun commented on products/views.py
> +                category_id     = request.GET["category_id"]
```suggestion
                category_id     = request.GET.get("category_id", 1) 
```

2021-07-09 05:52 UTC, Kang-kyunghun commented
```python
{
    "MESSAGE" : "SUCCESS",
    "result"  : {
            "category" : {},
            "products" : [{},{}]
},

```

2021-07-09 06:49 UTC, heesu-ahn commented
수정하였습니다

2021-07-09 07:53 UTC, Kang-kyunghun requested changes

2021-07-09 07:53 UTC, Kang-kyunghun commented on products/views.py
> +class ProductView(View) :
```suggestion
class ProductsView(View) :
```

2021-07-09 07:53 UTC, Kang-kyunghun commented on products/views.py
> +        try :
```suggestion
    def get(self,request) :
        try :
```

2021-07-09 07:55 UTC, Kang-kyunghun commented
1. for 문으로 되어 있는 부분을 list comprehension으로 바꿔보세요.
2. filter 조건을 Q() 객체를 이용해서 바꿔보세요.
3. 데이터 관련해서 질문 주셨던 거는 저도 조금 더 고민해 보겠습니다.

2021-07-09 08:01 UTC, heesu-ahn commented
>     2\. Q()

답변 코멘트 옵션이 막혀 있어서 이렇게 보냅니다
네 수정하겠습니다

2021-07-09 08:10 UTC, heesu-ahn commented
리스트 컴프리핸션 보고 있는데 이해가 잘 되지 않는 부분이 있는데 혹시 물어볼 수 있나요?

2021-07-09 09:13 UTC, heesu-ahn commented
수정해서 올려놨습니다

2021-07-12 11:45 UTC, heesu-ahn commented
수정 내용 : 경훈님 코드 받기 전에 혼자서 짜보고 7시쯤 받은 내용과 비교해서 약간 차이가 나는 부분만 수정하였음
코드 최적화 진행하였음
이상입니다.

2021-07-13 01:15 UTC, Kang-kyunghun requested changes

2021-07-13 01:15 UTC, Kang-kyunghun commented on products/views.py
> +                                            .annotate(max_stock = Max('option__stocks'))\
이거 data 잘 나오나요?? annotate 연속으로 사용하면 조건 하나 더 달아줘야 하는 걸로 알고 있는데, 정확한 data가 나오는지 확인해 보세요.

2021-07-13 01:15 UTC, Kang-kyunghun commented on products/views.py
> +                                            .order_by(options[sort_by])[offset: offset+limit]]
offset과 limit가 단순 더하기로 하면 원하는데로 페이지네이션이 되지 않습니다.
예를 들어 offset=1, limit=10이면 페이지가 1칸 이동해야 하는데, 데이터만 하나 이동하게 됩니다.

2021-07-13 01:16 UTC, Kang-kyunghun commented
카테고리 관련 이미지를 받는 것에 대해 문제가 생겼다고 들었습니다. 
해당 뷰에 카테고리 이미지와 설명을 주는 코드를 추가해야 할 것 같습니다.

2021-07-13 01:19 UTC, heesu-ahn commented on products/views.py
> +                                            .annotate(max_stock = Max('option__stocks'))\
데이터는 잘 나오는지 확인해보았습니다
![image](https://user-images.githubusercontent.com/77618489/125375263-b9302480-e3c3-11eb-8e58-6400f73e0578.png)

2021-07-13 01:20 UTC, heesu-ahn commented on products/views.py
> +                                            .order_by(options[sort_by])[offset: offset+limit]]
일단은 데이터가 한칸씩 이동하는 것이  의도한 바는 맞습니다
제품을 슬라이드처럼 한칸 한칸 옆으로 이동하는 기능입니다

2021-07-13 01:21 UTC, heesu-ahn commented
> 카테고리 관련 이미지를 받는 것에 대해 문제가 생겼다고 들었습니다.
> 해당 뷰에 카테고리 이미지와 설명을 주는 코드를 추가해야 할 것 같습니다.

카테고리를 동명님 네브에서 보내주는 것으로 수정하여서 제쪽에서는 카테고리 관련해서 보내주는 것이 없습니다

2021-07-13 01:28 UTC, heesu-ahn commented on products/views.py
> +                                            .order_by(options[sort_by])[offset: offset+limit]]
프론트 엔드와 다시 상의해서 페이지 * 리밋으로 하는 것으로 수정보기로 합의하였습니다
수정해서 다시 올리겠습니다

2021-07-13 04:03 UTC, heesu-ahn commented
듀플 나는 문제 처리해서 다시 푸시 하였습니다

2021-07-13 07:08 UTC, heesu-ahn commented
아마 한준님 브런치랑 제가 컨플릭트 발생하는가 본데 pull 해서 고쳐야 되나요 아니면 한준님이 고치고 나서 제가 pull 해야 하는 건가요?

2021-07-13 08:16 UTC, Kang-kyunghun commented
LGTM~~!!

2021-07-13 08:16 UTC, merged